# Trigger deploy with secrets configured
name: Deploy via ftp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: FTP Deploy Main Site & Jornada
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }} 
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: "."
        remoteDir: "public_html/casa-em-ordem"

    - name: FTP Deploy Quiz Subdomain
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }} 
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: "casa-em-ordem-quiz"
        remoteDir: "public_html/casa-em-ordem-quiz"
